[package]
name = "jetstream"
version = "0.1.0"
edition = "2021"

[dependencies]
atmo = { workspace = true, features = ["jetstream"] }
futures = { workspace = true }
pretty_env_logger = "0.5"
tokio = { workspace = true, features = ["full"] }
