[package]
name = "atmo_jetstream"
version = "0.1.0"
edition = "2021"

[dependencies]
atmo_api = { workspace = true }
atmo_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
