[package]
name = "atmo"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "atmo_codegen",
]

[workspace.dependencies]
atmo = { path = "." }
cid = "0.11.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"

[dependencies]
jiff = "0.1.13"
cid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.16"
multibase = "0.9.1"
multihash-derive = "0.9.1"
