[package]
name = "neophron"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "neophron_codegen",
]

[workspace.dependencies]
neophron = { path = "." }
cid = "0.11.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"

[dependencies]
jiff = "0.1.13"
cid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.16"
