[package]
name = "bluemorpho_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
bluemorpho = { workspace = true }
heck = "0.5.0"
proc-macro2 = "1.0.88"
quote = "1.0.37"
serde_json = { workspace = true }
serde_path_to_error = "0.1.16"
syn = "2.0.82"
walkdir = "2.5.0"
