[package]
name = "atmo_api"
version = "0.1.0"
edition = "2021"

[dependencies]
atmo = { workspace = true }
cid = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }
