[package]
name = "session"
version = "0.1.0"
edition = "2021"

[dependencies]
atmo = { workspace = true }
dialoguer = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }
